<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>ProjectNamePlaceholder.Api</AssemblyName>
    <RootNamespace>ProjectNamePlaceholder.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ProjectNamePlaceholder.Application/ProjectNamePlaceholder.Application.csproj" />
    <ProjectReference Include="../ProjectNamePlaceholder.Infrastructure/ProjectNamePlaceholder.Infrastructure.csproj" />
    <ProjectReference Include="../ProjectNamePlaceholder.Persistence/ProjectNamePlaceholder.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
  </ItemGroup>
</Project>
